title: Richard Startin's Blog
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-twitter-plugin
permalink: /posts/:title
google_analytics: UA-107180613-2

github_username:  richardstartin

markdown: kramdown

header_pages: 
  - about.md

defaults:
  - scope:
      path: ""
      type: "posts"
collections:
    posts:
        output: true
